/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.banco.view;

import br.com.banco.core.Banco;
import br.com.banco.service.BancoService;
import br.com.banco.service.ContaCorrenteService;

import javax.swing.*;

/**
 *
 * @author jgabr
 */
public class HomeBancoGUI extends javax.swing.JDialog {

    private final Banco banco;
    private final BancoService bancoService;
    private final ContaCorrenteService contaService;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeBancoGUI.class.getName());

    /**
     * Creates new form HomeBancoGUI
     */
    public HomeBancoGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.banco = new Banco();
        this.bancoService = new BancoService(banco);
        this.contaService = new ContaCorrenteService(banco);

        try {
            bancoService.carregarDeArquivo("contas.txt");
        } catch (java.io.IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Falha ao carregar: " + e.getMessage());
        }

        initComponents();
        setLocationRelativeTo(parent);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        btnCriarContas = new javax.swing.JButton();
        btnListarContas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCriarContas.setText("Criar Contas");
        btnCriarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarContasActionPerformed(evt);
            }
        });

        btnListarContas.setText("Listar Contas");
        btnListarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarContasActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerenciador de Contas Bancárias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCriarContas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(btnListarContas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarContas)
                    .addComponent(btnCriarContas))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarContasActionPerformed
        CriarContaGUI dlg = new CriarContaGUI(
                (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
                true,
                bancoService // usa o mesmo Banco em memória
        );
        dlg.setVisible(true);
    }//GEN-LAST:event_btnCriarContasActionPerformed

    private void btnListarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarContasActionPerformed
        try {
            br.com.banco.view.ListContaGUI dlg = new br.com.banco.view.ListContaGUI(
                            (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
                            true,
                            bancoService,
                            contaService
                    );
            dlg.setVisible(true);
        } catch (Throwable t) {
            t.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Erro abrindo lista: " + t.getMessage());
        }
    }//GEN-LAST:event_btnListarContasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                HomeBancoGUI dialog = new HomeBancoGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarContas;
    private javax.swing.JButton btnListarContas;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
